### ISSUE TITLE
Images uploaded with an iphone can be upside down.

### ISSUE THREAD

**Issue by wanchopeblanco** [Folkloreatelier/laravel-image#11]
I have found that images uploaded from an iphone or just taken from an iphone would be in an incorrect rotation. This is because of the iphone rotating its photos by modifying the exif information and not actually the photo.

So the question would be how to turn or rotate the image to the correct rotation by reading the exif information?

Thanks by the way

**Comment by dmongeau** [comment]
I will add it to built-in filters but for now, this library is based on Imagine and they do have an Autorotate filter that you can use this way:

```php

    use Imagine\Filter\Basic\Autorotate;

    $image = Image::open('/path/to/uploaded/mobile/image.png');
    $autorotate = new Autorotate();
    $autorotate->apply($image)->save('/path/to/rotated/image.png');
```

or you could define a custom filter for it:
```php
    use Imagine\Filter\Basic\Autorotate;

    Image::filter('autorotate', function($image)
    {
        $autorotate = new Autorotate();
        return $autorotate->apply($image);
    });
```

and then use it this way:
```html
<img src="<?=Image::url('/path/to/image.jpg', array('autorotate'))?>" />
```

**Comment by wanchopeblanco** [comment]
Thanks for the quick reply,

I couldnt make it work, metadata always returned null and autorate filter always returned the same image. I ended up using this code
```php
$exif = exif_read_data($path, 'IFD0');
		$rotation 	= 0;
		if(!empty($exif['Orientation'])) {
		    switch($exif['Orientation']) {
		        case 8:
		            $rotation = 90;
		            break;
		        case 3:
		            $rotation = 180;
		            break;
		        case 6:
		            $rotation = -90;
		            break;
		    }
		}

// Crop image and watermark it
$img = Image::make($path, ['width' => 800, 'height' => 540, 'crop' => true, 'rotate' => $rotation]);
```
