### ISSUE TITLE
Integration in Laravel 5.1

### ISSUE THREAD

**Issue by adw-cr** [Folkloreatelier/laravel-image#17]
Hello, i want use this package in  Laravel 5.1, is possible?

Thanks

**Comment by dmongeau** [comment]
Yes, it's compatible with Laravel 5.1

**Comment by adw-cr** [comment]
Perfect, this steps like of L4 on L5?

**Comment by dmongeau** [comment]
The steps described here https://github.com/Folkloreatelier/laravel-image are for Laravel 5
