### ISSUE TITLE
Support for AWS S3

### ISSUE THREAD

**Issue by vics80** [Folkloreatelier/laravel-image#18]
Hi,

Is possible to add compatibility with AWS S3? Or CloudFront maybe?

I have all the images in S3 and woud like to use some library like this or Croppa

**Comment by dmongeau** [comment]
I need this in one project, so this is something i'm working on right now!

**Comment by dmongeau** [comment]
It's now possible to use S3 or any other filesystem from laravel via the proxy feature. You can check the config/image.php for options.

**Comment by kfahmi** [comment]
can i see your image setting? for uploading to s3 using folklore image @dmongeau

**Comment by anuragrath** [comment]
Do we have any documentation for uploading to S3? Finding it difficult to make it working.
Thanks,

**Comment by dmongeau** [comment]
You should check the `v1` branch which will soon be released as 1.0 (currently finishing the documentation). It support multiple sources for your image (and Laravel Filesystems so AWS S3). The documentation is here: https://folkloreatelier.gitbooks.io/laravel-image (still working on it)

Let me know if you need help

**Comment by anuragrath** [comment]
Cool. I would go through this. 
Also if you can confirm this would be the flow.

When we request for a image url, it would check if the image exists
If the image exists, the url would be returned
If it doesn't exists, the image would be created & then url is returned

If my understanding is correct, what I see is that for every image request there is an overhead of existence check.

Would like to hear your views on this. @dmongeau
