### ISSUE TITLE
Support for custom image saving path

### ISSUE THREAD

**Issue by nicolasbinet** [Folkloreatelier/laravel-image#19]
Is-it possible to save the generated images to a different folder than the one the images are in, example :
from "/my/upload/image/cache.jpg"
to "/cache/my/upload/image/cache.jpg"

**Comment by rulatir** [comment]
Bump!

**Comment by dmongeau** [comment]
This features is added in v0.3.1. You can use a custom path by using the config `write_path`

Let me know if there is any problem
