### ISSUE TITLE
Auto compute height

### ISSUE THREAD

**Issue by amatz5** [Folkloreatelier/laravel-image#20]
Hi,

is there a way to autocompute the height? i will just give the width that i want to crop and the height will auto compute base on the width.

Example : Image width = 1000, height = 500
and i want to crop the image by giving the width size only,
width = 500, then the height will be 250, depend on how many percent the width will less that was also implement to height.

**Comment by dmongeau** [comment]
If you only specify the `width` parameter or the `height` parameter, it will resize only with this.

So for example, if you have you 1000x500 image and you do:

```php
Image::make('/path/to/image.jpg', [
    'width' => 500
])->save('/path/to/resized/image.jpg');
```

You will get a 500x250 image

**Comment by amatz5** [comment]
thanks its working now.
