### ISSUE TITLE
Fix for laravel 5.2

### ISSUE THREAD

**Issue by kozlikov** [Folkloreatelier/laravel-image#21]
fix please laravel 5.2

Class: Folklore\Image\ImageController;

replace line: use Illuminate\Foundation\Bus\DispatchesCommand;
on: use Illuminate\Foundation\Bus\DispatchesJobs;

and load trait
replace line: use DispatchesCommand, ValidatesRequests;
on: use DispatchesJobs, ValidatesRequests;

thanx

**Comment by blyleven** [comment]
Yes, please update this.

**Comment by dmongeau** [comment]
Updated in 4d10dd0

**Comment by blyleven** [comment]
Thank you! Happy new year!






On Fri, Jan 1, 2016 at 3:50 AM -0800, "David Mongeau-Petitpas" <notifications@github.com> wrote:












Updated in 4d10dd0

**Comment by tacone** [comment]
Actually you don't need to remove support for Laravel 5.1 (LTS), as the modified version works just fine.

I just changed composer.json https://github.com/tacone/laravel-image/commit/392be10440533b128d3a7dea953f6ae4553ea65c (don't mind the commit message, it's working)
