### ISSUE TITLE
Limit only the specified type and size

### ISSUE THREAD

**Issue by agafonovlelik** [Folkloreatelier/laravel-image#26]
I have now made several appeals:

http://localhost/uploads/11-image(_x501).jpg
http://localhost/uploads/11-image(_x601).jpg
http://localhost/uploads/11-image(_x700).jpg
http://localhost/uploads/11-image(200x300-crop).jpg

And each time create a miniature disk of the desired size. That's cool, but I risk filling the disk. I only need:

http://localhost/uploads/11-image(_x90).jpg
http://localhost/uploads/11-image(200x300-crop).jpg

All the rest you dismiss. How to do it?

**Comment by dmongeau** [comment]
You should use Custom filters, and define what are the sizes(and any manipulation) you need and then in the config restrict to use only custom filters so it won't be possible for anybody to call the url with random sizes and fill your disk.

I'm currently on vacation but if you look in the wiki there is a section about custom filters

**Comment by agafonovlelik** [comment]
I need manipulation only with some templates. I used (шт image.php setting) the pattern parameter and it worked:
	'url_parameter' => '-image({options})',
        'pattern' => '^(.*)\-image\(((?:\_x235|120x160\-crop))\)\.(jpg|jpeg|png|gif|JPG|JPEG|PNG|GIF)$',
I can only create ...-image(_x235) and ...image(160x120) that I need
