### ISSUE TITLE
image resize regeneration problem

### ISSUE THREAD

**Issue by mojbenzcar** [Folkloreatelier/laravel-image#27]
I am using Image::url('uploads/imagename',400, 400), image exists but it is not regerating the image and throwing 404 error. I am using nginx server.   
eg. http://server_url/uploads/imagename-image(400x400).jpg

**Comment by dmongeau** [comment]
Does the image exists relative to the public folder?

**Comment by mojbenzcar** [comment]
problem was nginx server configuration
    location ~*  \.(jpg|jpeg|png|gif|ico|css|js|woff)$ {
        expires 365d;
    }
Which prevented the generating the image.
@fixed
