### ISSUE TITLE
Option to scale only the images width

### ISSUE THREAD

**Issue by dersvenhesse** [Folkloreatelier/laravel-image#28]
Hi there,
I have a small feature suggestion / idea.

If you'd like an image to be only scaled to a specific width and don't care for the height, you currently have to use an URL like:

    image02-image(175x9999).jpg

Instead I'd be really neat to use something like one of this: `image02-image(175x*).jpg`  or `image02-image(175x0).jpg` or `image02-image(width-175).jpg` or something similar.

What do you think of this?

**Comment by dmongeau** [comment]
It's already possible.

```
image02-image(175x_).jpg
```

Or using the facade to create the url:

```php
Image::url('image02.jpg', 175);

//or

Image::url('image02.jpg',[
    'width' => 175
]);
```
