### ISSUE TITLE
Laravel 5.0 compatibility

### ISSUE THREAD

**Issue by goranata** [Folkloreatelier/laravel-image#3]
Hi, just wondering if you plan to extend this plugin, to be compatible with L5 ?

Thanks in advance,

**Comment by mauserrifle** [comment]
You could check out my fork for now:
https://github.com/Qballinternet/laravel-image

It has changes for L5

**Comment by dmongeau** [comment]
It is now compatible with Laravel 5.0 starting from version 0.2
