### ISSUE TITLE
Route cache generation not possible due Closure

### ISSUE THREAD

**Issue by mauserrifle** [Folkloreatelier/laravel-image#5]
The following code should just use a Controller:

    $app->make('router')->get('{path}', function($path) use ($app)

Because cache generation may fail now because of `laravel-image`:

    php artisan route:cache
    Route cache cleared!
    
    
                                                                         
      [LogicException]                                                   
      Unable to prepare route [{path}] for serialization. Uses Closure.

**Comment by dmongeau** [comment]
Fixed with version 0.2.2
