### ISSUE TITLE
Registering custom filters - Laravel 5

### ISSUE THREAD

**Issue by joearcher** [Folkloreatelier/laravel-image#6]
The documentation on custom filters recommends registering filters in the `app/start/global.php` file. 
As of the current version of Laravel this file no longer exists. I've tried defining a filter as middleware but this did not work. Anyone have an idea of the best place to register these filters now we don't have a global.php file?

**Comment by dmongeau** [comment]
Yes, you should use service providers and declare your filters in the `boot`  method. Either you use the `AppServiceProvider` or you create a new one specific to Image, like `ImageServiceProvider`. Don't forget to add it in the `config/app.php` file

**Comment by joearcher** [comment]
Great, thanks for your help.
