### ISSUE TITLE
Quality of scaled image

### ISSUE THREAD

**Issue by ZengineAlex** [Folkloreatelier/laravel-image#8]
Hello,

I have tried to scale down some images with your package and it works. But I'm wondering about the quality of the resized ones...they seem to a little blurred. Is this normal or do you have an idea where this can come from? Maybe I have done something wrong.

Greetings,

ZengineAlex

**Comment by dmongeau** [comment]
There is a `quality` option that you can adjust (0 to 100). It should solve your problem. Let me know

**Comment by ZengineAlex** [comment]
i have written for excample 'quality' => 100 within the options array from Image::make.

i tried in quality 0, 50 and 100 and there was no difference.

**Comment by ZengineAlex** [comment]
well i see that maybe the problem is that i use GD instead of imagick. i will switch to imagick and see whether is works better.

**Comment by dmongeau** [comment]
Is it a png file? Because I think the quality only affect jpg image in Imagine.
